apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm-presidio.fullname" . }}-secret
  labels:
    {{- include "litellm-presidio.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded master key for LiteLLM
  master-key: {{ .Values.litellm.masterKey | b64enc | quote }}
